#!/usr/bin/env python3
"""Compile the title tune into MACRO-11 tables for the PPU beeper.

    music_gen.py src/res/music/title.txt --out build/data_music.mac

The UKNC has a one-bit speaker, so the three voices are mixed by XORing
three square waves onto it.  Each voice in src/ppu.mac is a 16-bit
phase accumulator: the engine adds the voice's increment once per pass
of its idle loop and flips the speaker on the carry, so the tone is
inc/65536 of the loop rate.  The AY tone the original played is
1773400 / (16 * period) Hz, so the increment is simply MU_K / period.

The AY sound module needs none of that arithmetic - it is fed the
original's periods as they stand - so the same pitch index also
addresses AY_PERIODS.

Emits:

    MU_PERIODS   word per distinct pitch (phase increment, 0 = rest)
    AY_PERIODS   word per distinct pitch (the AY period itself)
    MU_CH0/1/2   {pitch index, frames} byte pairs, 0377 ends the voice
"""

import argparse
import sys
from pathlib import Path

# increment = MU_K / AY period.  MU_K folds in the PPU loop rate and is
# calibrated by measuring the emulator's audio output (see the README);
# raise it to raise every pitch.
MU_K = 688500
MAXPITCH = 250


def read_channels(path):
    chans, cur = {}, None
    for raw in Path(path).read_text().splitlines():
        line = raw.split(";")[0].strip()
        if not line:
            continue
        if line.startswith("channel "):
            cur = int(line.split()[1])
            chans[cur] = []
            continue
        p, n = (int(x) for x in line.split())
        chans[cur].append((p, n))
    return [chans[i] for i in sorted(chans)]


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    ap.add_argument("input")
    ap.add_argument("--out", required=True)
    ap.add_argument("--force", action="store_true")
    a = ap.parse_args(argv)
    out = Path(a.out)
    if out.exists() and not a.force:
        sys.exit(f"error: {out} exists (use --force)")

    chans = read_channels(a.input)
    pitches = sorted({p for ch in chans for p, _ in ch if p})
    if len(pitches) > MAXPITCH:
        sys.exit(f"error: {len(pitches)} distinct pitches, at most {MAXPITCH}")
    index = {p: i + 1 for i, p in enumerate(pitches)}

    lines = [f"; generated by tools/music_gen.py from {a.input}",
             "MU_PERIODS:", "\t\t.WORD\t0"]
    for p in pitches:
        inc = max(1, min(0o77777, MU_K // p))
        lines.append(f"\t\t.WORD\t{inc:o}\t; AY period {p} = "
                     f"{110837.5 / p:.0f} Hz")
    lines += ["AY_PERIODS:", "\t\t.WORD\t0"]
    for p in pitches:
        lines.append(f"\t\t.WORD\t{p:o}\t; {110837.5 / p:.0f} Hz")
    total = 0
    for c in range(3):
        ev = chans[c] if c < len(chans) else []
        lines.append(f"MU_CH{c}:")
        row = []
        for p, n in ev:
            n = max(1, min(255, n))
            row += [index.get(p, 0), n]
            total += 1
            if len(row) >= 16:
                lines.append("\t\t.BYTE\t" + ",".join(f"{v:o}" for v in row))
                row = []
        if row:
            lines.append("\t\t.BYTE\t" + ",".join(f"{v:o}" for v in row))
        lines.append("\t\t.BYTE\t377")
    lines.append("\t\t.EVEN")
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}: {len(pitches)} pitches, {total} notes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
