#!/usr/bin/env python3
"""Assemble the scenery display lists into MACRO-11 source.

    objects_gen.py src/res/objects/objects.txt --out build/data_lists.mac

Emits:

    LIST_TAB   one word per list: the byte offset of the list inside
               LISTS (the 'call' opcode stores the same offset, so the
               blob is position independent)
    LISTS      the byte code itself, exactly the machine documented in
               .claude/docs/re-notes.md
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import resources as R


def emit_bytes(lines, label, blob, per=16):
    lines.append(f"{label}:")
    for i in range(0, len(blob), per):
        chunk = blob[i:i + per]
        lines.append("\t\t.BYTE\t" + ",".join(f"{b:o}" for b in chunk))
    lines.append("\t\t.EVEN")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    ap.add_argument("input")
    ap.add_argument("--out", required=True)
    ap.add_argument("--force", action="store_true")
    a = ap.parse_args(argv)
    out = Path(a.out)
    if out.exists() and not a.force:
        sys.exit(f"error: {out} exists (use --force)")

    lists = R.read_lists(a.input)
    addr, blob = R.layout_lists(lists, 0)
    lines = [f"; generated by tools/objects_gen.py from {a.input}",
             f"; {len(lists)} display lists, {len(blob)} bytes"]
    for name, num in sorted(R.read_aliases(a.input).items()):
        lines.append(f"L_{name}\t= {num}.")
    lines.append("LIST_TAB:")
    for i in range(len(lists)):
        lines.append(f"\t\t.WORD\t{addr[i]:o}\t; list {i}")
    emit_bytes(lines, "LISTS", blob)
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}: {len(lists)} lists, {len(blob)} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
