#!/usr/bin/env python3
"""Compile the sprite sheets into MACRO-11 source.

    sprites_gen.py --player src/res/sprites/player.txt
                   --small  src/res/sprites/small.txt
                   --out build/data_sprites.mac

Emits PLAYER_SPR (3 bytes x 32 lines per frame) and SMALL_SPR (2 bytes
x 16 lines per frame), both with bit 0 = leftmost pixel so the sprite
plotter can shift them straight into the plane bytes.
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import resources as R

PLAYER_W, PLAYER_H = 3, 32
SMALL_W, SMALL_H = 2, 16


def revbits(b):
    r = 0
    for i in range(8):
        if b & (1 << i):
            r |= 1 << (7 - i)
    return r


def emit(lines, label, frames, w, h, name):
    lines.append(f"; {name}: {len(frames)} frames of {w * 8}x{h}")
    lines.append(f"{label}:")
    for i, f in enumerate(frames):
        if len(f) != w * h:
            sys.exit(f"error: {name} frame {i} is {len(f)} bytes, want {w * h}")
        lines.append(f"\t\t; frame {i}")
        for y in range(h):
            row = f[y * w:(y + 1) * w]
            lines.append("\t\t.BYTE\t" +
                         ",".join(f"{revbits(b):o}" for b in row))
    lines.append("\t\t.EVEN")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    ap.add_argument("--player", required=True)
    ap.add_argument("--small", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--force", action="store_true")
    a = ap.parse_args(argv)
    out = Path(a.out)
    if out.exists() and not a.force:
        sys.exit(f"error: {out} exists (use --force)")

    player = R.read_frames(a.player, PLAYER_W)
    small = R.read_frames(a.small, SMALL_W)
    lines = ["; generated by tools/sprites_gen.py"]
    emit(lines, "PLAYER_SPR", player, PLAYER_W, PLAYER_H, "player")
    emit(lines, "SMALL_SPR", small, SMALL_W, SMALL_H, "16x16 sprites")
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}: {len(player)} player + {len(small)} small frames")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
