#!/usr/bin/env python3
"""Compile the game strings into MACRO-11 source.

    text_gen.py src/res/text/strings.txt --out build/strings.mac

Input: one "LABEL|text" line per string (';' starts a comment).  The
port draws text as tiles and the glyph bank holds the font at tile
index = ASCII code, so a string is simply its ASCII bytes followed by
a 0 terminator.  Lowercase is uppercased (the font has no lowercase).
"""

import argparse
import sys
from pathlib import Path


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    ap.add_argument("input")
    ap.add_argument("--out", required=True)
    ap.add_argument("--force", action="store_true")
    a = ap.parse_args(argv)
    out = Path(a.out)
    if out.exists() and not a.force:
        sys.exit(f"error: {out} exists (use --force)")

    lines = [f"; generated by tools/text_gen.py from {a.input}"]
    n = 0
    for raw in Path(a.input).read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith(";") or "|" not in line:
            continue
        label, text = line.split("|", 1)
        text = text.upper()
        for ch in text:
            if not (32 <= ord(ch) < 96):
                sys.exit(f"error: {label}: character {ch!r} is not in the font")
        vals = ",".join(f"{ord(c):o}" for c in text) or "0"
        lines.append(f"S_{label.strip()}:\t.BYTE\t{vals},0")
        lines.append("\t\t.EVEN")
        n += 1
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}: {n} strings")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
