#!/usr/bin/env python3
"""Compile the 8x8 glyph bank into MACRO-11 source.

    tiles_gen.py src/res/tiles/tiles.txt --out build/data_tiles.mac [--force]

Emits two labels:

    TILE_GFX   one tile per 8 bytes, bit 0 = LEFTMOST pixel (UKNC plane
               order, the reverse of the ZX Spectrum), so a glyph byte
               goes straight into a video plane
    TILE_WT    one byte per tile: how many pixels it lights, used by
               zone.mac to weigh the inks when it picks a row palette
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import resources as R


def revbits(b):
    r = 0
    for i in range(8):
        if b & (1 << i):
            r |= 1 << (7 - i)
    return r


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    ap.add_argument("input")
    ap.add_argument("--out", required=True)
    ap.add_argument("--force", action="store_true")
    a = ap.parse_args(argv)
    out = Path(a.out)
    if out.exists() and not a.force:
        sys.exit(f"error: {out} exists (use --force)")

    tiles = R.read_tiles(a.input)
    lines = [f"; generated by tools/tiles_gen.py from {a.input}",
             f"; {len(tiles)} tiles", "TILE_GFX:"]
    for i, g in enumerate(tiles):
        vals = ",".join(f"{revbits(b):o}" for b in g)
        lines.append(f"\t\t.BYTE\t{vals}\t; {i}")
    lines += ["\t\t.EVEN", "TILE_WT:"]
    wt = [sum(bin(b).count("1") for b in g) for g in tiles]
    for i in range(0, len(wt), 16):
        lines.append("\t\t.BYTE\t" + ",".join(f"{v:o}" for v in wt[i:i + 16]))
    lines.append("\t\t.EVEN")
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}: {len(tiles)} tiles ({len(tiles) * 9} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
