#!/usr/bin/env python3
"""Assemble the zone table and the live-object boxes into MACRO-11.

    zones_gen.py src/res/zones/zones.txt --boxes src/res/objects/boxes.txt
                 --out build/data_zones.mac

Emits:

    ZONE_TAB   one word per zone: the byte offset of its object list
               inside ZONE_DATA
    ZONE_DATA  {row, col, object} triples, 0377-terminated per zone
    BOXTAB     four bytes per object id (dx, w, dy, h) in cell units;
               w = 0 marks an object that is pure scenery
    NZONES     the number of zones
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import resources as R

NOBJECTS = 62


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    ap.add_argument("input")
    ap.add_argument("--boxes", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--force", action="store_true")
    a = ap.parse_args(argv)
    out = Path(a.out)
    if out.exists() and not a.force:
        sys.exit(f"error: {out} exists (use --force)")

    zones = R.read_zones(a.input)
    boxes = R.read_boxes(a.boxes)

    blob, offs = bytearray(), []
    for z in zones:
        offs.append(len(blob))
        for row, col, obj in z:
            blob += bytes([row & 0xFF, col & 0xFF, obj & 0xFF])
        blob.append(0xFF)

    lines = [f"; generated by tools/zones_gen.py from {a.input}",
             f"; {len(zones)} zones, {len(blob)} bytes of placement data",
             f"NZONES\t= {len(zones)}.", "ZONE_TAB:"]
    for i, o in enumerate(zones):
        lines.append(f"\t\t.WORD\t{offs[i]:o}\t; zone {i}")
    lines.append("ZONE_DATA:")
    for i in range(0, len(blob), 15):
        lines.append("\t\t.BYTE\t" + ",".join(f"{b:o}" for b in blob[i:i + 15]))
    lines.append("\t\t.EVEN")
    lines.append("BOXTAB:")
    for obj in range(NOBJECTS):
        dx, w, dy, h = boxes.get(obj, (0, 0, 0, 0))
        vals = ",".join(f"{v & 0xFF:o}" for v in (dx, w, dy, h))
        lines.append(f"\t\t.BYTE\t{vals}\t; object {obj}")
    lines.append("\t\t.EVEN")
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}: {len(zones)} zones, {len(blob)} bytes")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
